language: ruby
rvm:
- 2.1

install: gem install jekyll

script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

# after building, copy the site into the gh-pages branch
# and push back to Github
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- '([ "${TRAVIS_PULL_REQUEST}" = "false" ] && git push --force --quiet "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${PRODUCTION_TARGET_BRANCH} > /dev/null 2>&1) || ([ "${TRAVIS_PULL_REQUEST}" != "false" ] && git push --force --quiet "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${STAGING_TARGET_BRANCH} > /dev/null 2>&1) || echo "WARNING: git push to {GITHUB_REPO} failed"'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/literarymachine/jekyll-bare.git
  - STAGING_TARGET_BRANCH: pages-staging
  - PRODUCTION_TARGET_BRANCH: pages-production
  - secure: foo
  - secure: bar

