language: ruby
rvm:
- 2.1

install: gem install jekyll

script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

# after building, copy the site into the gh-pages branch
# and push back to Github
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch:
    - master
    - develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO=github.com/literarymachine/jekyll-bare.git
  - STAGING_TARGET_BRANCH=pages-staging
  - PRODUCTION_TARGET_BRANCH=pages-production
  - secure: foo
  - secure: bar

